export type Trip = {
  id: string;
  image: string;
  host: string;
  title: string;
  location?: string;
  date?: string;
  tags?: string[];
  likes?: number;
  joined?: string;
  spotsLeft?: number;
  status?: "Upcoming" | "Ongoing" | "Completed";
  visibility?: "Public" | "Private";
  joinPolicy?: "Open" | "Approval";
  country?: string;
  continent?: string;
  summary?: string;
  category?: "Beach" | "Mountains" | "City" | "Adventure";
  membersJoined?: number;
  maxMembers?: number;
};
